// Generated by CoffeeScript 1.6.3
(function() {
  (function() {
    var debug;
    if (typeof debug !== "undefined") {
      throw new Error("debug object already defined!");
    }
    debug = {};
    debug.assertObjectValid = function(obj) {
      if (!obj) {
        throw new Exception("Invalid object!");
      }
      if ($.isPlainObject(obj)) {
        throw new Error("Input is not an object! It is a " + typeof obj);
      }
    };
  })();

}).call(this);

/*
//@ sourceMappingURL=debug.map
*/
