// Generated by CoffeeScript 1.6.3
(function() {
  var fs, http, path, port, url;

  http = require("http");

  url = require("url");

  path = require("path");

  fs = require("fs");

  port = process.argv[2] || 8888;

  http.createServer(function(request, response) {
    var filename, uri;
    uri = url.parse(request.url).pathname;
    filename = path.join(process.cwd(), uri);
    path.exists(filename, function(exists) {
      if (!exists) {
        response.writeHead(404, {
          "Content-Type": "text/plain"
        });
        response.write("404 Not Found\n");
        response.end();
        return;
      }
      if (fs.statSync(filename).isDirectory()) {
        filename += "/index.html";
      }
      fs.readFile(filename, "binary", function(err, file) {
        var contentType, ext;
        if (err) {
          response.writeHead(500, {
            "Content-Type": "text/plain"
          });
          response.write(err + "\n");
          response.end();
          return;
        }
        contentType = "text/plain";
        ext = path.extname(filename);
        switch (ext) {
          case ".html":
            contentType = "text/html";
            break;
          case ".css":
            contentType = "text/css";
            break;
          case ".js":
            contentType = "text/javascript";
        }
        console.log("Incoming ext: " + ext + ", content: " + contentType);
        response.writeHead(200, {
          "Content-Type": contentType
        });
        response.write(file, "binary");
        response.end();
      });
    });
  }).listen(parseInt(port, 10));

  console.log("Static file server running at\n  => http://localhost:" + port + "/\nCTRL + C to shutdown");

}).call(this);
